### ISSUE TITLE
the problem with running in Unity

### ISSUE THREAD

**Issue by PlatinumFlow** [Iggyyy/horrorUnity#1]
Good afternoon, I can't launch the project in unity, it shows an error. Can you tell me how to launch the project correctly?

**Comment by istepka** [comment]
Hi! That's some old project of mine, which I coded up in high school, back when I was thinking that I'm going to be a game developer. If I remember correctly, I only uploaded the folder with C# scripts, because the entire project had a few GBs worth of assets and stuff like that. 

I managed to find the entire project in my archive :) Here, I uploaded it to some fileshare website: [https://filetransfer.io/data-package/HERYxoGn#link](https://filetransfer.io/data-package/HERYxoGn#link) . It says that this link is going to expire in 24 days.
